#!/usr/bin/python
import os, sys

# setup configuration area before loading anything else
main_config_dir = os.path.expanduser('~/.dosbox-pykde')
if not os.path.exists(main_config_dir):
    os.mkdir(main_config_dir)

if not os.path.isdir(main_config_dir):
    raise StandardError, 'main_config_dir: %s is not a directory' % main_config_dir

directories = {}.fromkeys(['games', 'configs', 'screenshots', 'capture'])
for dir_key in directories:
    path = os.path.join(main_config_dir, dir_key)
    directories[dir_key] = path
    if not os.path.exists(path):
        os.mkdir(path)

from kdecore import KCmdLineArgs

from dboxpykde.kdelib.application import MainApplication, AboutData
from dboxpykde.kdelib.mainwindow import MainWindow

from dboxpykde.config import config
from dboxpykde.gamesdata import GameDataHandler
from dboxpykde.filemanagement.main import GameFilesHandler
from dboxpykde.dosbox import Dosbox
from dboxpykde.kdelib.base import excepthook


if __name__ == '__main__':
    aboutData = AboutData()
    # I don't understand this part
    KCmdLineArgs.init(sys.argv, aboutData)
    sys.excepthook = excepthook
    #raise StandardError, 'testing an error'

    # setup application
    app = MainApplication()
    app.config = config
    app.main_config_dir = main_config_dir
    app.main_dosbox_path = config.get('DEFAULT', 'main_dosbox_path')
    app.game_datahandler = GameDataHandler(directories)
    app.game_fileshandler = GameFilesHandler(app.game_datahandler)
    app.dosbox = Dosbox(app)
    
    # setup dcop and register the application
    dcop = app.dcopClient()
    appid = dcop.registerAs('dosbox-pykde')
    win = MainWindow(None)
    win.show()
    # set main window in application
    app.setMainWidget(win)
    # run the application
    app.exec_loop()

    
