#!/usr/bin/python
import os, sys

# setup configuration area before loading anything else
main_config_dir = os.path.expanduser('~/.dosbox-pykde')
if not os.path.exists(main_config_dir):
    os.mkdir(main_config_dir)

if not os.path.isdir(main_config_dir):
    raise StandardError, 'main_config_dir: %s is not a directory' % main_config_dir

games_dir = os.path.join(main_config_dir, 'games')
if not os.path.exists(games_dir):
    os.mkdir(games_dir)

dbox_configs_dir = os.path.join(main_config_dir, 'configs')
if not os.path.exists(dbox_configs_dir):
    os.mkdir(dbox_configs_dir)

dbox_main_screenshots_dir = os.path.join(main_config_dir, 'capture')
if not os.path.exists(dbox_main_screenshots_dir):
    os.mkdir(dbox_main_screenshots_dir)
    

from kdecore import KCmdLineArgs

from widgets import AboutData
from widgets import MainApplication
from widgets import MainWindow

from config import config
from gamesdata import GameDataHandler
from filemanager import GameFilesHandler
from dosbox import Dosbox

if __name__ == '__main__':
    aboutData = AboutData()
    # I don't understand this part
    KCmdLineArgs.init(sys.argv, aboutData)

    # setup application
    app = MainApplication()
    app.config = config
    app.main_config_dir = main_config_dir
    app.game_datahandler = GameDataHandler(games_dir)
    app.game_fileshandler = GameFilesHandler(app.game_datahandler)
    app.dosbox = Dosbox(app)
    
    # setup dcop and register the application
    dcop = app.dcopClient()
    appid = dcop.registerAs('dosbox-pykde')
    win = MainWindow(None)
    win.show()
    # set main window in application
    app.setMainWidget(win)
    # run the application
    app.exec_loop()

    
