#!/usr/bin/python
import os, sys

_dev_modpath ='DOSBOX_PYKDE_DEVELOPMENT_MODULES_PATH'
_modpaths = ['/usr/local/share/dosbox-pykde/modules',
             '/usr/share/dosbox-pykde/modules']
if _dev_modpath in os.environ:
    _modpaths.insert(1, _dev_modpath)
for path in _modpaths:
    if os.path.isdir(path) and path not in sys.path:
        sys.path.insert(1, path)
del _modpaths, _dev_modpath

# setup configuration area before loading anything else
main_config_dir = os.path.expanduser('~/.dosbox-pykde')
if not os.path.exists(main_config_dir):
    os.mkdir(main_config_dir)

if not os.path.isdir(main_config_dir):
    raise StandardError, 'main_config_dir: %s is not a directory' % main_config_dir

directories = {}.fromkeys(['games', 'configs', 'screenshots', 'capture'])
for dir_key in directories:
    path = os.path.join(main_config_dir, dir_key)
    directories[dir_key] = path
    if not os.path.exists(path):
        os.mkdir(path)

from kdecore import KCmdLineArgs

from widgets import AboutData
from widgets import MainApplication
from widgets import MainWindow

from config import config
from gamesdata import GameDataHandler
from filemanager import GameFilesHandler
from dosbox import Dosbox

if __name__ == '__main__':
    aboutData = AboutData()
    # I don't understand this part
    KCmdLineArgs.init(sys.argv, aboutData)

    # setup application
    app = MainApplication()
    app.config = config
    app.main_config_dir = main_config_dir
    app.main_dosbox_path = config.get('DEFAULT', 'main_dosbox_path')
    app.game_datahandler = GameDataHandler(directories)
    app.game_fileshandler = GameFilesHandler(app.game_datahandler)
    app.dosbox = Dosbox(app)
    
    # setup dcop and register the application
    dcop = app.dcopClient()
    appid = dcop.registerAs('dosbox-pykde')
    win = MainWindow(None)
    win.show()
    # set main window in application
    app.setMainWidget(win)
    # run the application
    app.exec_loop()

    
