#!/usr/bin/python
import os, sys

_dev_modpath ='DOSBOX_PYKDE_DEVELOPMENT_MODULES_PATH'
_modpaths = ['/usr/local/share/dosbox-pykde/modules',
             '/usr/share/dosbox-pykde/modules']
if _dev_modpath in os.environ:
    _modpaths.insert(1, _dev_modpath)
for path in _modpaths:
    if os.path.isdir(path) and path not in sys.path:
        sys.path.insert(1, path)
del _modpaths, _dev_modpath

# setup configuration area before loading anything else
main_config_dir = os.path.expanduser('~/.dosbox-pykde')
if not os.path.exists(main_config_dir):
    os.mkdir(main_config_dir)

if not os.path.isdir(main_config_dir):
    raise StandardError, 'main_config_dir: %s is not a directory' % main_config_dir

directories = {}.fromkeys(['games', 'configs', 'screenshots', 'capture'])
for dir_key in directories:
    path = os.path.join(main_config_dir, dir_key)
    directories[dir_key] = path
    if not os.path.exists(path):
        os.mkdir(path)

from qt import SIGNAL, SLOT
from qt import QApplication
        
# main application class
# we define the class here for now
class MainApplication(QApplication):
    def __init__(self, args):
        QApplication.__init__(self, args)
        # in case something needs done before quitting
        self.connect(self, SIGNAL('aboutToQuit()'), self.quit)
        self.appname = 'MainApplication'
        
    def quit(self):
        QApplication.quit(self)

# We have to start the application before any other widgets are
# imported, to get qApp to point back to the python instance of the
# application.
app = MainApplication(sys.argv)
sys.modules['qt'].__dict__['qApp'] = app

#from widgets import AboutData
#from widgets import MainApplication
#from qtwin.widgets import MainApplication

#from qtwin.widgets import MainWindow
from qtwin.mainwindow import MainWindow

from config import config
from gamesdata import GameDataHandler
from filemanager import GameFilesHandler
from dosbox import Dosbox

if __name__ == '__main__':
    # setup application
    #app = MainApplication(sys.argv)
    #sys.modules['qt'].__dict__['qApp'] = app
    app.myconfig = config
    app.main_config_dir = main_config_dir
    app.main_dosbox_path = config.get('DEFAULT', 'main_dosbox_path')
    app.game_datahandler = GameDataHandler(directories)
    app.game_fileshandler = GameFilesHandler(app.game_datahandler)
    app.dosbox = Dosbox(app)
       
    win = MainWindow(None)
    win.show()
    # set main window in application
    app.setMainWidget(win)
    # run the application
    app.exec_loop()

    
